spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kcinemadb?useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 7777
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
